# This workflow will install Python dependencies, run tests with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10.0, 3.11.0]
    env:
      DISPLAY: :99.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Installation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python setup.py install
    - name: Setup system requirements
      run: |
        export QT_DEBUG_PLUGINS=1
        sudo apt-get update
        sudo apt-get install xvfb libnotify-bin libcairo2-dev \
          gir1.2-gtk-3.0 libpango1.0-dev libxcb-xtest0-dev \
          libxcb-icccm4-dev libxcb-randr0-dev libxcb-keysyms1-dev \
          libxcb-xinerama0-dev libdbus-1-dev libxdg-basedir-dev \
          libstartup-notification0-dev imagemagick libxcb1-dev \
          libxcb-shape0-dev libxcb-util0-dev libx11-xcb-dev \
          libxcb-cursor-dev libxcb-xkb-dev libxcb-xfixes0-dev \
          libxkbcommon-dev libxkbcommon-x11-dev libxkbcommon-x11-0
      if: matrix.os == 'ubuntu-latest'
    - name: Test (Ubuntu)
      run: |
        xvfb-run python -m gopem --test
      if: matrix.os == 'ubuntu-latest'
    - name: Test (Windows)
      run: |
        python -m gopem --test
      if: matrix.os != 'ubuntu-latest'
    - name: Other tests requirements Installation
      run: |
        python rsrc/requirements-splitter.py
        pip install --upgrade --upgrade-strategy=only-if-needed -r test-requirements.txt
      if: matrix.python-version == 3.8
    - name: Version check
      run: |
        python rsrc/version_check.py
      if: matrix.python-version == 3.8
    - name: Other tests
      run: |
          python -m vulture --min-confidence 65 --sort-by-size gopem rsrc setup.py
          python -m bandit -r gopem
          python -m pydocstyle -v --match-dir=gopem
      if: matrix.python-version == 3.8
